multipleAttributes:
  - jsonField: attachmentFileName
    dbField: file_name
    dbTableAlias: da
    joinInfo:
      - order: 1
        reference:
          table: menu_item
          alias: mi
          column: id
        join:
          table: documents
          alias: d
          column: menu_item_id
        type: LEFT_JOIN
      - order: 2
        reference:
          table: documents
          alias: d
          column: id
        join:
          table: document_attachments
          alias: da
          column: document_id
        type: LEFT_JOIN
  - jsonField: attachmentExtension
    dbField: extension
    dbTableAlias: da
    joinInfo:
      - order: 1
        reference:
          table: menu_item
          alias: mi
          column: id
        join:
          table: documents
          alias: d
          column: menu_item_id
        type: LEFT_JOIN
      - order: 2
        reference:
          table: documents
          alias: d
          column: id
        join:
          table: document_attachments
          alias: da
          column: document_id
        type: LEFT_JOIN