simpleAttributes:
  - jsonField: id
    dbField: id
    fieldType: NUMERIC
  - jsonField: title
    dbField: title
    fieldType: STRING
  - jsonField: path
    dbField: path
    fieldType: STRING
  - jsonField: isActive
    dbField: is_active
    fieldType: BOOLEAN
  - jsonField: inheritParentPermissions
    dbField: inherit_parent_permissions
    fieldType: BOOLEAN
  - jsonField: availableEveryone
    dbField: available_everyone
    fieldType: BOOLEAN
  - jsonField: createDate
    dbField: create_date
    fieldType: OFFSET_DATE_TIME
  - jsonField: lastUpdateDate
    dbField: last_update_date
    fieldType: OFFSET_DATE_TIME