attributes:
  - attributeType: SIMPLE
    jsonField: id
    dbField: id
    fieldType: NUMERIC
  - attributeType: SIMPLE
    jsonField: title
    dbField: title
    fieldType: STRING
  - attributeType: SIMPLE
    jsonField: path
    dbField: path
    fieldType: STRING
  - attributeType: SIMPLE
    jsonField: isActive
    dbField: is_active
    fieldType: BOOLEAN
  - attributeType: SIMPLE
    jsonField: inheritParentPermissions
    dbField: inherit_parent_permissions
    fieldType: BOOLEAN
  - attributeType: SIMPLE
    jsonField: availableEveryone
    dbField: available_everyone
    fieldType: BOOLEAN
  - attributeType: SIMPLE
    jsonField: createDate
    dbField: create_date
    fieldType: OFFSET_DATE_TIME
  - attributeType: SIMPLE
    jsonField: lastUpdateDate
    dbField: last_update_date
    fieldType: OFFSET_DATE_TIME
  - attributeType: MULTIPLE
    jsonField: attachmentFileName
    dbField: file_name
    dbTableAlias: da
    fieldType: STRING
    joinInfo:
      - order: 1
        reference:
          table: menu_item
          alias: mi
          column: id
        join:
          table: documents
          alias: d
          column: menu_item_id
        type: LEFT_JOIN
      - order: 2
        reference:
          table: documents
          alias: d
          column: id
        join:
          table: document_attachments
          alias: da
          column: document_id
        type: LEFT_JOIN
  - attributeType: MULTIPLE
    jsonField: attachmentExtension
    dbField: extension
    dbTableAlias: da
    fieldType: STRING
    joinInfo:
      - order: 1
        reference:
          table: menu_item
          alias: mi
          column: id
        join:
          table: documents
          alias: d
          column: menu_item_id
        type: LEFT_JOIN
      - order: 2
        reference:
          table: documents
          alias: d
          column: id
        join:
          table: document_attachments
          alias: da
          column: document_id
        type: LEFT_JOIN
  - attributeType: MULTIPLE
    jsonField: documentId
    dbField: id
    dbTableAlias: d
    fieldType: NUMERIC
    joinInfo:
      - order: 1
        reference:
          table: menu_item
          alias: mi
          column: id
        join:
          table: documents
          alias: d
          column: menu_item_id
        type: LEFT_JOIN