attributes:
  - type: SIMPLE
    json:
      key: id
    db:
      column: id
      type: java.lang.Long

  - type: SIMPLE
    json:
      key: title
    db:
      column: title
      type: java.lang.String

  - type: SIMPLE
    json:
      key: path
    db:
      column: path
      type: java.lang.String

  - type: SIMPLE
    json:
      key: isActive
    db:
      column: is_active
      type: java.lang.Boolean

  - type: SIMPLE
    json:
      key: inheritParentPermissions
    db:
      column: inherit_parent_permissions
      type: java.lang.Boolean

  - type: SIMPLE
    json:
      key: availableEveryone
    db:
      column: available_everyone
      type: java.lang.Boolean

  - type: SIMPLE
    json:
      key: createDate
    db:
      column: create_date
      type: java.time.OffsetDateTime

  - type: SIMPLE
    json:
      key: lastUpdateDate
    db:
      column: last_update_date
      type: java.time.OffsetDateTime

  - type: MULTIPLE
    json:
      key: attachmentFileName
    db:
      column: file_name
      type: java.lang.String
      joinInfo:
        - order: 1
          reference:
            table: menu_item
            column: id
          join:
            table: documents
            column: menu_item_id
          type: LEFT_JOIN
        - order: 2
          reference:
            table: documents
            column: id
          join:
            table: document_attachments
            column: document_id
          type: LEFT_JOIN

  - type: MULTIPLE
    json:
      key: attachmentExtension
    db:
      column: extension
      type: java.lang.String
      joinInfo:
        - order: 1
          reference:
            table: menu_item
            column: id
          join:
            table: documents
            column: menu_item_id
          type: LEFT_JOIN
        - order: 2
          reference:
            table: documents
            column: id
          join:
            table: document_attachments
            column: document_id
          type: LEFT_JOIN

  - type: MULTIPLE
    json:
      key: documentId
    db:
      column: id
      type: java.lang.String
      joinInfo:
        - order: 1
          reference:
            table: menu_item
            column: id
          join:
            table: documents
            column: menu_item_id
          type: LEFT_JOIN